# Generated by Django 5.2.17 on 2026-09-26 08:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('delivery', models.CharField(choices=[('pickup', 'Store pickup'), ('delivery', 'Delivery')], max_length=10)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('location', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid (test)')], default='pending', max_length=12)),
                ('fulfillment_status', models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('ready', 'Ready for pickup'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='GHS. Leave blank for contact-for-price products.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('tag', models.CharField(blank=True, max_length=40)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('long_description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, help_text='Upload a replacement product photo.', upload_to='products/')),
                ('image_path', models.CharField(blank=True, help_text='Existing storefront image path, e.g. /products/photo.webp. Upload takes priority.', max_length=300)),
                ('image_alt', models.CharField(blank=True, max_length=300)),
                ('highlights', models.TextField(blank=True, help_text='One highlight per line.')),
                ('visual', models.CharField(choices=[('phone-pro', 'phone-pro'), ('macbook', 'macbook'), ('ipad', 'ipad'), ('watch', 'watch'), ('airpods', 'airpods')], default='phone-pro', max_length=30)),
                ('tone', models.CharField(default='sand', max_length=30)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide the product from the storefront.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.category')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('selections', models.JSONField(default=dict)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Stable option ID, e.g. storage or color.')),
                ('label', models.CharField(max_length=60)),
                ('values', models.TextField(help_text='One allowed value per line, e.g. 128 GB, then 256 GB on the next line.')),
                ('position', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='store.product')),
            ],
            options={
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('product', 'key'), name='unique_product_option')],
            },
        ),
    ]
