# Generated by Django 5.2.17 on 2026-10-07 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_payment_method_alter_order_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(help_text='Match a color from Product Color above, e.g. Red.', max_length=60)),
                ('image', models.ImageField(upload_to='products/colors/')),
                ('image_alt', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_images', to='store.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'color'), name='unique_product_color_image')],
            },
        ),
    ]
